### ISSUE TITLE
Duplicate code copied when using code animation

### ISSUE THREAD

**Issue by marcocrowe** [Martinomagnifico/reveal.js-copycode#1]
In this example, the code is copied 2 times

```html
<section>
	<h2>The Hello World Example</h2>
	<div class="sl-block" data-block-type="code">
		<div class="sl-block-content notranslate">
			<pre><code class="language-java hljs" data-line-numbers="1-8|4-7" data-fragment-index="1">package example;
public class HelloWorldExample
{
	public static void main(String[] args)
	{
		System.out.print("Hello World.");
	}
}
</code></pre>
		</div>
	</div>
</section>
```

The cause of the error is here

https://github.com/Martinomagnifico/reveal.js-copycode/blob/169049d4dbce2e97322732d35a9fdd70244eefcd/plugin/copycode/copycode.js#L57

The fix is to change L57 to 

```js
return trigger.nextElementSibling.firstChild;
```

And make the same change in the esm version here

https://github.com/Martinomagnifico/reveal.js-copycode/blob/169049d4dbce2e97322732d35a9fdd70244eefcd/plugin/copycode/copycode.esm.js#L51

**Comment by Martinomagnifico** [comment]
Hi Mark, thanks for the good catch! This is now fixed.
