### ISSUE TITLE
No longer working after version 1.0.4

### ISSUE THREAD

**Issue by jenwirth** [Martinomagnifico/reveal.js-copycode#12]
Hi,

I have been trying to update our use of this plugin. It works fine for version 1.0.4, but from 1.1.0 onwards it stops working.

No error message, just no "copy" button.

The way we initialize the plugin for 1.0.4

```typescript
// @ts-ignore
import CopyCode from "reveal.js-copycode/plugin/copycode/copycode.esm"
…
Reveal.initialize({
  …
  plugins: [CopyCode, RevealZoom, RevealSearch, RevealMarkdown, Highlight, RevealNotes, RevealMath.KaTeX]
});
```

EDIT: we are using reveal 5.0.5

**Comment by Martinomagnifico** [comment]
I'll get back to you on this. Have some time next week I think.

**Comment by Martinomagnifico** [comment]
Did you try it like this:
```
<script type="module">
    import Reveal from '/dist/reveal.esm.js';
    import RevealHighlight from '/plugin/highlight/highlight.esm.js';
    import CopyCode from '/plugin/copycode/copycode.esm.js';
      
    const deck = document.querySelector(".reveal");
      
    let revealdeck = new Reveal(deck);
    revealdeck.initialize({
        history: true,
        overview: false,
        center: true,
        margin: 0.15,
        controlsTutorial: false,
        copycode: { timeout: 1200 },
        plugins: [ RevealHighlight, CopyCode ]
    });
</script>
```
?

**Comment by jenwirth** [comment]
That did not help. Same problem, no warnings, errors, just no "copy" button.

**Comment by Martinomagnifico** [comment]
Is there a possibility to send me a minimum project example as a zip file? Can be done here or via email.

**Comment by jenwirth** [comment]
I've had a colleague look into it and he mentioned that the plugin is loading a resource by adding a stylesheet `link`. The scheme of the URL is "file://" when using it as an npm dependency.

**Comment by Martinomagnifico** [comment]
Thanks. I’ll look into it.

**Comment by Martinomagnifico** [comment]
If somehow the css does not load, you can try to enter it via the csspath option.

```
Reveal.initialize({
    // ...
    copycode: {
        csspath: "./path/to/copycode.css"
    },
    plugins: [ CopyCode ]
});
```

Still need to find some time to look into the root cause of the issue. If you could create a bare-minimum zip would be the fastest way to a real solution.

**Comment by Martinomagnifico** [comment]
@jenwirth I changed the loading of CSS in another Reveal.js plugin ([Mulitimodal](https://github.com/Martinomagnifico/reveal.js-multimodal)). 

The issue of auto-loading CSS through the means currently implemented by CopyCode is that it looks at the current script path, then uses that same path for the CSS. When working with modules as in the example in the Readme, that works, but when the plugin is installed via npm, and a main/app js then uses `import`, then the path of that main js is then seen as the path, which is not the same path as the plugin. 

Regular users (who don't use npm) can just load the plugin and all will work. 

Although the plugin is able to check if the plugin is loaded as a module, that does not always mean that it is installed through npm, and won't help with getting the correct path anyway.

The way I used it in [Mulitimodal](https://github.com/Martinomagnifico/reveal.js-multimodal) is to try and load the CSS anyway (for regular users) but that function can be turned off through the `cssautoload` option. Just set it to false. You can then use `import`, where your setup (React/Webpack or whatever) is probably able to load the CSS correctly.

Let me know if that works for you, then I'll add that same setup in this plugin. In the end it will benefit most users.

**Comment by hayesall** [comment]
Adding my two cents since I'm running into similar CSS woes.

I'm experimenting with different build systems (specifically [vite](https://vitejs.dev/)), where the build/tree-shaking step removes unused assets at build time.

Overwriting `csspath` will *sometimes* work during development, but dynamically loading in resources based on a string means it isn't obvious those assets actually get used: resulting in a `404: copycode.css`

**Comment by Martinomagnifico** [comment]
Thanks @hayesall, that’s indeed why I’m trying out another plugin (which is still a pre-1.0.0 version, still have issues with Firefox) where the `cssautoload` config is a new option. The user can turn that off and manually load the css with import. Let me know if that works for you.

Putting the whole CSS into the JS would be another option.

**Comment by Martinomagnifico** [comment]
Putting the whole CSS into the JS would be another option.

**Comment by Martinomagnifico** [comment]
@jenwirth The latest version has a `cssautoload` option. Set it to false if you want to `import` with a bundler like Webpack or Parcel.
