### ISSUE TITLE
Extra indentation with `data-line-numbers` again

### ISSUE THREAD

**Issue by hayesall** [Martinomagnifico/reveal.js-copycode#13]
When a `<pre>` has `data-line-numbers` text like this gets copied:

```javascript
let why = `Because we always want to copy code

	           during our presentations, right?`
```

but when I take out `data-line-numbers` and add in `data-trim`, it works as expected:

```javascript
let why = `Because we always want to copy code
           during our presentations, right?`
```

---

This is similar to #2 but exists in 1.1.8 and on the master branch at 3ea17556600a93cb608c9fa32f5cc0f9fd29de30

I could reproduce this in Chrome and Firefox using the [online demo slidedeck](https://martinomagnifico.github.io/reveal.js-copycode/demo/demo.html#/), but I added an extra demo slide in https://github.com/hayesall/reveal.js-copycode/tree/data-line-numbers-debug

brief demo:

https://github.com/Martinomagnifico/reveal.js-copycode/assets/11916674/cc75539f-22eb-4ef1-a30a-592228c9bc2f

**Comment by hayesall** [comment]
I don't have a solid solution yet, but it feels like this is partially due to trying to do an entire query selector over each `code` on copy.

https://github.com/Martinomagnifico/reveal.js-copycode/blob/3ea17556600a93cb608c9fa32f5cc0f9fd29de30/src/plugin/js/functions/do-clipboard.js#L4-L7

Instead of a regex find-and-replace: since `hljs` renders code blocks as tables, the simplest way might be to iterate over the table and skip anything with a `hljs-ln-numbers` class.

maybe:

```javascript
var first_block = document.querySelectorAll('code')[0];

var table = first_block.querySelector('table');

for (let row of table.rows) {
  for (let cell of row.cells) {
    if (cell.className.match("hljs-ln-numbers")) {
      continue
    } else {
      console.log(cell.innerText);      
    }
  }
}
```

**Comment by Martinomagnifico** [comment]
Hi Alexander, good catch! Safari does not have this issue, but indeed Chrome and Firefox and Edge do.
