### ISSUE TITLE
Extra indentation copied when code has line numbers enabled

### ISSUE THREAD

**Issue by danbst** [Martinomagnifico/reveal.js-copycode#2]
Revealjs has support for line numbers in code blocks.

When I copy code from that block, pasted code is indented. This must be the problem with line numbers in revealjs, because when I copy manually I still have those indentation symbols during paste in editor (VS Code).

I understand this more a problem with revealjs, but would be great if CopyCode could handle this "line-numbers" usecase and remove extra indent.

## Details
1. This is how my code block is defined (using markdown syntax)
![image](https://user-images.githubusercontent.com/743057/145008831-8063a1c8-4952-467a-ba40-8292e80fdd42.png)
2. This is how it is rendered by revealjs
![image](https://user-images.githubusercontent.com/743057/145008889-07d03cc4-864a-4c6d-b308-6f3826110ae9.png)
3. This is how it is pasted into editor after being copied by CopyCode
![image](https://user-images.githubusercontent.com/743057/145008981-fe10d1a9-b298-4761-8390-a2e50bb1e9c5.png)

**Comment by Martinomagnifico** [comment]
Fixed in version 1.0.3

**Comment by danbst** [comment]
It wasn't fixed for me. I've tried it in a different browser (was testing in Firefox and tried Google Chrome) and found it is **browser-dependent bug**!

It works fine in Chrome, but creates indents in Firefox (even in CopyCode version 1.0.3).

So I have a workaround for now -- not to use Firefox.
