### ISSUE TITLE
"Copy" button visible when code block is a hidden fragment

### ISSUE THREAD

**Issue by danbst** [Martinomagnifico/reveal.js-copycode#3]
When using fragments in presentation, and making code block a (hidden by default) fragment, "Copy" button is still visible.

It should not be visible until fragment becomes visible.

![image](https://user-images.githubusercontent.com/743057/145014255-7e11761c-e362-47e0-999b-2787f3e927a0.png)

**Comment by Martinomagnifico** [comment]
Fixed in version 1.0.3

**Comment by danbst** [comment]
that was fast! Thanks, it works.
