### ISSUE TITLE
Closing Tag Missing

### ISSUE THREAD

**Issue by Jole94** [Martinomagnifico/reveal.js-copycode#4]
In Setup Part of the Readme, there are closing tags missing for the reveal.js script and the clipboard.js script
```
<script src="dist/reveal.js"> ***
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"> ***
<script src="plugin/copycode/copycode.js"></script>
<script>
	Reveal.initialize({
		// ...
		plugins: [ CopyCode ]
	});
</script> ```

**Comment by Martinomagnifico** [comment]
Script tags with content , where the actual JavaScript is inside the HTML markup, can be closed with …`</script>`.

However, the lines where you put the *** do not have such content. There is only an src reference.  You might then think that such tags are self-closing, like `<img/>` or `<link/>`. For the `<script>` tag, that is not the case. That means that the Readme is correct.

**Comment by Martinomagnifico** [comment]
I had it wrong, readme is now updated.
