### ISSUE TITLE
clipboard.min.js:7 Uncaught Error: Invalid "target" value, use a valid Element

### ISSUE THREAD

**Issue by Kexplx** [Martinomagnifico/reveal.js-copycode#5]
Hi,

I am getting this error when i click the "COPY" button on a code snippet.

![image](https://user-images.githubusercontent.com/29175032/191712145-148c1463-0a12-46c8-adce-38c4f61edf67.png)

**Comment by Martinomagnifico** [comment]
Can you replicate it on something like codepen? Then I can check it out.

**Comment by javicatalaiesdoctorbalmis** [comment]
I have the same problem. Fresh reveal.js basic installation (just download de repo) and adding the plugin (copy folder in plugins, and adding script reference and plugin name in the plugins list. Open index.html in the browser and gets the error.

**Comment by Martinomagnifico** [comment]
Hi @javicatalaiesdoctorbalmis, I've tested the same steps as you did. No errors here. I'm curious what it could be. And of course, I'll fix it if I can. 

Could you host this example somewhere or send me a zip of it?
And @Kexplx did you find a cause of it?

**Comment by Martinomagnifico** [comment]
Bump

**Comment by javicatalaiesdoctorbalmis** [comment]
Hi,

I changed reveal index.html by your demo.html, and it works fine. I didn't found what in index.html is causing the problem. So I made an HTML basic template from your demo and now everything is ok.

**Comment by Martinomagnifico** [comment]
Thanks for getting back!

**Comment by g1eb** [comment]
I had the same issue pop up when `code` and `pre` tags are on separate lines, if they are on the same line it works just fine..
