### ISSUE TITLE
Can you remove changes of font-size for all `pre` block?

### ISSUE THREAD

**Issue by AntonShevchuk** [Martinomagnifico/reveal.js-copycode#6]
https://github.com/Martinomagnifico/reveal.js-copycode/blob/98b262e26ef9cc3be2dec39a6324dfbc1da608f5/plugin/copycode/copycode.css#L40

**Comment by Martinomagnifico** [comment]
Sure. Will be fixed tomorrow afternoon.

**Comment by Martinomagnifico** [comment]
😀 This was fixed yesterday.
